---

- name: Create a directory if it does not exist
  file:
    path: "{{ project_path }}"
    state: directory
    mode: '0755'
  tags:
    - copy_image

- name: Copy imge to remote
  copy:
    src: "{{ image }}.tar"
    dest: "{{ project_path }}/{{ image }}.tar"
    mode: '0744'
  tags:
    - copy_image

- name: Load docker image
  command:
    cmd: "docker load -i {{ project_path }}/{{ image }}.tar"
  tags:
    - copy_image
    
#- name: Run docker image
 # command:
 #   cmd: "docker container run -d --name web-server -p 8080:8080 {{ image }}"
    
- name: Update docker image
  command:
    cmd: "docker container stop web-server"
    cmd: "docker container rm web-server"
    cmd: "docker container run -d --name web-server -p 8080:8080 {{ image }}"
